USE ROLE TRAININGDBA;
USE WAREHOUSE XSMALL;
USE DATABASE TRAINING;
USE SCHEMA PUBLIC;

-- Snowflake also support EXTERNAL tables
-- EXTERNAL TABLE: DEPOSITORS DATASET
CREATE OR REPLACE EXTERNAL TABLE TRAINING.PUBLIC.DEPOSITOR_RAW (
    ADDRESS VARCHAR AS (VALUE:ADDRESS::VARCHAR),
    BIRTH_DATE VARCHAR AS (VALUE:BIRTH_DATE::VARCHAR),
    CITY VARCHAR AS (VALUE:CITY::VARCHAR),
    COUNTRY VARCHAR AS (VALUE:COUNTRY::VARCHAR),
    DEPOSITOR_BRANCH VARCHAR AS (VALUE:DEPOSITOR_BRANCH::VARCHAR),
    DEPOSITOR_ID VARCHAR AS (VALUE:DEPOSITOR_ID::VARCHAR),
    DEPOSITOR_TYPE_CODE VARCHAR AS (VALUE:DEPOSITOR_TYPE_CODE::VARCHAR),
    DEPOSITOR_UID VARCHAR AS (VALUE:DEPOSITOR_UID::VARCHAR),
    EMAIL VARCHAR AS (VALUE:EMAIL::VARCHAR),
    FIRST_NAME VARCHAR AS (VALUE:FIRST_NAME::VARCHAR),
    LAST_NAME VARCHAR AS (VALUE:LAST_NAME::VARCHAR),
    PHONE VARCHAR AS (VALUE:PHONE::VARCHAR),
    POSTAL_CODE VARCHAR AS (VALUE:POSTAL_CODE::VARCHAR),
    STATE VARCHAR AS (VALUE:STATE::VARCHAR)
)
LOCATION = @TRAINING.PUBLIC.STAGE_EXTERNAL_DEPOSITORS
AUTO_REFRESH = FALSE
FILE_FORMAT = (FORMAT_NAME = TRAINING.PUBLIC.FILE_FORMAT_JSON_GENERIC);

SELECT * FROM TRAINING.PUBLIC.DEPOSITOR_RAW SAMPLE(10 ROWS);
