-- ****************************** 1.- Warehouse ******************************
USE ROLE SYSADMIN;
CREATE OR REPLACE WAREHOUSE XSMALL COMMENT = "Generic Virtual Warehouse"
 WAREHOUSE_TYPE = STANDARD
 WAREHOUSE_SIZE = XSMALL
 MAX_CLUSTER_COUNT = 3
 MIN_CLUSTER_COUNT = 1
 SCALING_POLICY = ECONOMY
 AUTO_SUSPEND = 120
 AUTO_RESUME = TRUE
 INITIALLY_SUSPENDED = TRUE
 ENABLE_QUERY_ACCELERATION =FALSE;

-- ****************************** 1.- Database ******************************
USE ROLE SYSADMIN;
CREATE OR REPLACE DATABASE TRAINING COMMENT = "Snowflake Training database"
 DATA_RETENTION_TIME_IN_DAYS = 3;

-- ****************************** 2.- Schemas ******************************
USE ROLE ACCOUNTADMIN;
USE DATABASE TRAINING;
ALTER SCHEMA IF EXISTS TRAINING.PUBLIC ENABLE MANAGED ACCESS;

-- ****************************** 3.- Roles ******************************
USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE TRAININGDBA;
GRANT ROLE TRAININGDBA TO ROLE SYSADMIN;

-- ****************************** 4.- Grants ******************************
-- TASK
USE ROLE ACCOUNTADMIN;
GRANT EXECUTE TASK, EXECUTE MANAGED TASK ON ACCOUNT TO ROLE TRAININGDBA;

-- WAREHOUSE
USE ROLE SECURITYADMIN;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE TRAININGDBA;
GRANT USAGE, OPERATE, MODIFY ON WAREHOUSE XSMALL TO ROLE TRAININGDBA;

-- DATABASE
USE ROLE SECURITYADMIN;
GRANT ALL ON DATABASE TRAINING TO ROLE TRAININGDBA;
GRANT ALL ON ALL SCHEMAS IN DATABASE TRAINING TO ROLE TRAININGDBA;
